[cpu]
cycles=max
[dosbox]
captures=/Users/paulbieles/development/repton/my_repton/html5/tools/captures
[video]
vmemsize=8
[render]
aspect=false
[sdl]
windowresolution=960x600
output=opengl
[dos]
machine=vgaonly
[autoexec]
mount c /Users/paulbieles/development/repton/my_repton
c:
REPTON.EXE
